### ISSUE TITLE
Warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object in Akeneo/Archive/PackagesExtractor.php on line 25

### ISSUE THREAD

**Issue by nidup** [akeneo/nelson#12]
When running app/console nelson:pull-translations,

To git@github.com:nidup/pim-community-dev.git
 * [new branch]      1.5 -> 1.5
PHP Warning:  ZipArchive::extractTo(): Invalid or uninitialized Zip object in src/Akeneo/Archive/PackagesExtractor.php on line 25

**Comment by pierallard** [comment]
@nidup The behavior of Zip is different between PHP versions. Can you provide your PHP version then I will try to reproduce ?

**Comment by nidup** [comment]
PHP 5.6.11-1ubuntu3.3 (cli) I will take a look with my local env, it will be easier to fix

**Comment by nidup** [comment]
In fact I'm not able to reproduce it was a regression related to last changes on https://github.com/akeneo/php-crowdin-api/pull/34 as nelson uses alpha2 the issue was not visible
